name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
    steps:          
      - name: Install
        run: |
          sudo apt-get install googletest
          
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check CMake version
        run: |
          cmake --version
          
      - name: CMake
        run: |
          cmake . -DCMAKE_CXX_STANDARD=20
          
  windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-2022, windows-2019]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check CMake version
        run: |
          cmake --version
          
      - name: CMake
        run: |
          cmake . -DCMAKE_CXX_STANDARD=20
          
  mac:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
    steps:          
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check CMake version
        run: |
          cmake --version
          
      - name: CMake
        run: |
          cmake . -DCMAKE_CXX_STANDARD=20
          
